version: '3'

tasks:
  default:
    desc: "The default task" 
    deps: [run]

  ext:
    desc: "Build and Install extension"
    dir: ext
    cmds:
      - vsce package --allow-missing-repository
      # - code-server --uninstall-extension undefined_publisher.ext1
      - code-server --install-extension litessh-0.0.1.vsix
  
  run:
    cmds:
      - go run .
  
  install-r:
    cmds:
      - go install ./cmd/r