version: '3'

tasks:
  default:
    desc: "The default task" 
    deps: [run]

  ext:
    desc: "Build and Install extension"
    dir: ext
    cmds:
      - vsce package --allow-missing-repository
      # - code-server --uninstall-extension undefined_publisher.ext1
      - code-server --install-extension litessh-0.0.1.vsix
  
  run:
    cmds:
      - go run ./cmd/litessh
  
  install-r:
    cmds:
      - go install ./cmd/r

  build-mainland:
    desc: "Build the image in China Mainland"
    cmds:
      - docker pull registry.cn-hangzhou.aliyuncs.com/117503445-mirror/sync:linux.amd64.docker.io.library.archlinux.latest
      - docker tag registry.cn-hangzhou.aliyuncs.com/117503445-mirror/sync:linux.amd64.docker.io.library.archlinux.latest archlinux
      - docker build --pull=false -t 117503445/litessh -f ./scripts/docker/Dockerfile --build-arg CHINA_MIRROR=1 .
  run-image:
    deps: [build-mainland]
    cmds:
      - docker run --hostname=litessh -it --rm -p 4445:4444 -v /workspace/logs:/workspace/logs -v /workspace/config.toml:/workspace/config.toml -v /root/.ssh/id_ed25519:/root/.ssh/id_ed25519 117503445/litessh